/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author teu02
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenu();
        menuHospCadastrar = new javax.swing.JMenuItem();
        menuHospConsultar = new javax.swing.JMenuItem();
        menuCadQuartos = new javax.swing.JMenu();
        menuQuaCadastrar = new javax.swing.JMenuItem();
        menuQuaConsultar = new javax.swing.JMenuItem();
        menuCadFuncionarios = new javax.swing.JMenu();
        menuFunCadastrar = new javax.swing.JMenuItem();
        menuFunConsultar = new javax.swing.JMenuItem();
        menuCadFornecedores = new javax.swing.JMenu();
        menuForCadastrar = new javax.swing.JMenuItem();
        menuForConsultar = new javax.swing.JMenuItem();
        menuCadProdutos = new javax.swing.JMenu();
        menuProCadastrar = new javax.swing.JMenuItem();
        menuProConsultar = new javax.swing.JMenuItem();
        menuCadServicos = new javax.swing.JMenu();
        menuSerCadastrar = new javax.swing.JMenuItem();
        menuSerConsultar = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        menuResCadastrarReserva = new javax.swing.JMenuItem();
        menuResConsultarReserva = new javax.swing.JMenuItem();
        menuResFinalizarReserva = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuVendasProdutos = new javax.swing.JMenuItem();
        menuVendasServicos = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        menuFinConPag = new javax.swing.JMenu();
        menuFinConPagCadastrar = new javax.swing.JMenuItem();
        menuFinConPagConsultar = new javax.swing.JMenuItem();
        menuFinConRec = new javax.swing.JMenu();
        menuFinConRecCadastrar = new javax.swing.JMenuItem();
        menuFinConRecConsultar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelFinaceiro = new javax.swing.JMenu();
        menuRelFinanConPag = new javax.swing.JMenuItem();
        menuRelFinanConRec = new javax.swing.JMenuItem();
        menuRelFinanBalanco = new javax.swing.JMenuItem();
        menuRelReservas = new javax.swing.JMenu();
        menuRelResCadastrarReserva = new javax.swing.JMenuItem();
        menuRelResConsultarReserva = new javax.swing.JMenuItem();
        menuRelResFinalizarReserva = new javax.swing.JMenuItem();
        menuRelVendas = new javax.swing.JMenu();
        menuRelVenProdutos = new javax.swing.JMenuItem();
        menuRelVenServicos = new javax.swing.JMenuItem();
        menuRelHospedes = new javax.swing.JMenuItem();
        menuRelFuncionarios = new javax.swing.JMenuItem();
        menuRelFornecedores = new javax.swing.JMenuItem();
        menuSeguranca = new javax.swing.JMenu();
        menuSegFazBackup = new javax.swing.JMenuItem();
        menuSegRestBackup = new javax.swing.JMenuItem();
        menuFerramenta = new javax.swing.JMenu();
        menuFerTelaFundo = new javax.swing.JMenu();
        menuFerTFAdImagem = new javax.swing.JMenuItem();
        menuFerTFRemImagem = new javax.swing.JMenuItem();
        menuFerTFResPadrao = new javax.swing.JMenuItem();
        menuFerSobreSistema = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        menuCadastro.setText("Cadastros   |");

        menuCadHospede.setText("Hospedes");

        menuHospCadastrar.setText("Cadastrar");
        menuHospCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHospCadastrarActionPerformed(evt);
            }
        });
        menuCadHospede.add(menuHospCadastrar);

        menuHospConsultar.setText("Consultar");
        menuCadHospede.add(menuHospConsultar);

        menuCadastro.add(menuCadHospede);

        menuCadQuartos.setText("Quartos");

        menuQuaCadastrar.setText("Cadastrar");
        menuQuaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuaCadastrarActionPerformed(evt);
            }
        });
        menuCadQuartos.add(menuQuaCadastrar);

        menuQuaConsultar.setText("Consultar");
        menuQuaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuaConsultarActionPerformed(evt);
            }
        });
        menuCadQuartos.add(menuQuaConsultar);

        menuCadastro.add(menuCadQuartos);

        menuCadFuncionarios.setText("Funcionários");

        menuFunCadastrar.setText("Cadastrar");
        menuCadFuncionarios.add(menuFunCadastrar);

        menuFunConsultar.setText("Consultar");
        menuCadFuncionarios.add(menuFunConsultar);

        menuCadastro.add(menuCadFuncionarios);

        menuCadFornecedores.setText("Fornecedores");

        menuForCadastrar.setText("Cadastrar");
        menuCadFornecedores.add(menuForCadastrar);

        menuForConsultar.setText("Consultar");
        menuForConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuForConsultarActionPerformed(evt);
            }
        });
        menuCadFornecedores.add(menuForConsultar);

        menuCadastro.add(menuCadFornecedores);

        menuCadProdutos.setText("Produtos");

        menuProCadastrar.setText("Cadastrar");
        menuCadProdutos.add(menuProCadastrar);

        menuProConsultar.setText("Consultar");
        menuCadProdutos.add(menuProConsultar);

        menuCadastro.add(menuCadProdutos);

        menuCadServicos.setText("Serviços");

        menuSerCadastrar.setText("Cadastrar");
        menuCadServicos.add(menuSerCadastrar);

        menuSerConsultar.setText("Consultar");
        menuCadServicos.add(menuSerConsultar);

        menuCadastro.add(menuCadServicos);

        menu.add(menuCadastro);

        menuReservas.setText("Reservas   |");

        menuResCadastrarReserva.setText("Cadastrar Reserva");
        menuReservas.add(menuResCadastrarReserva);

        menuResConsultarReserva.setText("Consultar Reserva");
        menuReservas.add(menuResConsultarReserva);

        menuResFinalizarReserva.setText("Finalizar Reserva");
        menuReservas.add(menuResFinalizarReserva);

        menu.add(menuReservas);

        menuVendas.setText("Vendas   |");

        menuVendasProdutos.setText("Produtos");
        menuVendasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasProdutosActionPerformed(evt);
            }
        });
        menuVendas.add(menuVendasProdutos);

        menuVendasServicos.setText("Serviços");
        menuVendas.add(menuVendasServicos);

        menu.add(menuVendas);

        menuFinanceiro.setText("Financeiro   |");

        menuFinConPag.setText("Contas a Pagar");

        menuFinConPagCadastrar.setText("Cadastrar");
        menuFinConPag.add(menuFinConPagCadastrar);

        menuFinConPagConsultar.setText("Consultar");
        menuFinConPag.add(menuFinConPagConsultar);

        menuFinanceiro.add(menuFinConPag);

        menuFinConRec.setText("Contas a Receber");

        menuFinConRecCadastrar.setText("Cadastrar");
        menuFinConRec.add(menuFinConRecCadastrar);

        menuFinConRecConsultar.setText("Consultar");
        menuFinConRec.add(menuFinConRecConsultar);

        menuFinanceiro.add(menuFinConRec);

        jMenuItem1.setText("Balanço");
        menuFinanceiro.add(jMenuItem1);

        menu.add(menuFinanceiro);

        menuRelatorio.setText("Relatórios   |");

        menuRelFinaceiro.setText("Financeiro");

        menuRelFinanConPag.setText("Contas a Pagar");
        menuRelFinaceiro.add(menuRelFinanConPag);

        menuRelFinanConRec.setText("Contas a Receber");
        menuRelFinaceiro.add(menuRelFinanConRec);

        menuRelFinanBalanco.setText("Balanço");
        menuRelFinaceiro.add(menuRelFinanBalanco);

        menuRelatorio.add(menuRelFinaceiro);

        menuRelReservas.setText("Reservas");

        menuRelResCadastrarReserva.setText("Cadastrar Reserva");
        menuRelReservas.add(menuRelResCadastrarReserva);

        menuRelResConsultarReserva.setText("Consultar Reserva");
        menuRelReservas.add(menuRelResConsultarReserva);

        menuRelResFinalizarReserva.setText("Finalizar Reserva");
        menuRelReservas.add(menuRelResFinalizarReserva);

        menuRelatorio.add(menuRelReservas);

        menuRelVendas.setText("Vendas");

        menuRelVenProdutos.setText("Produtos");
        menuRelVendas.add(menuRelVenProdutos);

        menuRelVenServicos.setText("Serviços");
        menuRelVenServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelVenServicosActionPerformed(evt);
            }
        });
        menuRelVendas.add(menuRelVenServicos);

        menuRelatorio.add(menuRelVendas);

        menuRelHospedes.setText("Hospedes");
        menuRelatorio.add(menuRelHospedes);

        menuRelFuncionarios.setText("Funcionários");
        menuRelatorio.add(menuRelFuncionarios);

        menuRelFornecedores.setText("Fornecedores");
        menuRelatorio.add(menuRelFornecedores);

        menu.add(menuRelatorio);

        menuSeguranca.setText("Segurança   |");

        menuSegFazBackup.setText("Fazer Backup");
        menuSeguranca.add(menuSegFazBackup);

        menuSegRestBackup.setText("Restaurar Backup");
        menuSegRestBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSegRestBackupActionPerformed(evt);
            }
        });
        menuSeguranca.add(menuSegRestBackup);

        menu.add(menuSeguranca);

        menuFerramenta.setText("Ferramentas   |");

        menuFerTelaFundo.setText("Tela de Fundo");

        menuFerTFAdImagem.setText("Add Imagem");
        menuFerTelaFundo.add(menuFerTFAdImagem);

        menuFerTFRemImagem.setText("Remover Imagem");
        menuFerTelaFundo.add(menuFerTFRemImagem);

        menuFerTFResPadrao.setText("Reustarar Padrão");
        menuFerTelaFundo.add(menuFerTFResPadrao);

        menuFerramenta.add(menuFerTelaFundo);

        menuFerSobreSistema.setText("Sobre o Sistema");
        menuFerramenta.add(menuFerSobreSistema);

        menu.add(menuFerramenta);

        menuSair.setText("Sair   ");
        menu.add(menuSair);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuHospCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHospCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHospCadastrarActionPerformed

    private void menuQuaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuaConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuQuaConsultarActionPerformed

    private void menuQuaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuaCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuQuaCadastrarActionPerformed

    private void menuForConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuForConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuForConsultarActionPerformed

    private void menuVendasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVendasProdutosActionPerformed

    private void menuRelVenServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelVenServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelVenServicosActionPerformed

    private void menuSegRestBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSegRestBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSegRestBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuCadFornecedores;
    private javax.swing.JMenu menuCadFuncionarios;
    private javax.swing.JMenu menuCadHospede;
    private javax.swing.JMenu menuCadProdutos;
    private javax.swing.JMenu menuCadQuartos;
    private javax.swing.JMenu menuCadServicos;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuFerSobreSistema;
    private javax.swing.JMenuItem menuFerTFAdImagem;
    private javax.swing.JMenuItem menuFerTFRemImagem;
    private javax.swing.JMenuItem menuFerTFResPadrao;
    private javax.swing.JMenu menuFerTelaFundo;
    private javax.swing.JMenu menuFerramenta;
    private javax.swing.JMenu menuFinConPag;
    private javax.swing.JMenuItem menuFinConPagCadastrar;
    private javax.swing.JMenuItem menuFinConPagConsultar;
    private javax.swing.JMenu menuFinConRec;
    private javax.swing.JMenuItem menuFinConRecCadastrar;
    private javax.swing.JMenuItem menuFinConRecConsultar;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenuItem menuForCadastrar;
    private javax.swing.JMenuItem menuForConsultar;
    private javax.swing.JMenuItem menuFunCadastrar;
    private javax.swing.JMenuItem menuFunConsultar;
    private javax.swing.JMenuItem menuHospCadastrar;
    private javax.swing.JMenuItem menuHospConsultar;
    private javax.swing.JMenuItem menuProCadastrar;
    private javax.swing.JMenuItem menuProConsultar;
    private javax.swing.JMenuItem menuQuaCadastrar;
    private javax.swing.JMenuItem menuQuaConsultar;
    private javax.swing.JMenu menuRelFinaceiro;
    private javax.swing.JMenuItem menuRelFinanBalanco;
    private javax.swing.JMenuItem menuRelFinanConPag;
    private javax.swing.JMenuItem menuRelFinanConRec;
    private javax.swing.JMenuItem menuRelFornecedores;
    private javax.swing.JMenuItem menuRelFuncionarios;
    private javax.swing.JMenuItem menuRelHospedes;
    private javax.swing.JMenuItem menuRelResCadastrarReserva;
    private javax.swing.JMenuItem menuRelResConsultarReserva;
    private javax.swing.JMenuItem menuRelResFinalizarReserva;
    private javax.swing.JMenu menuRelReservas;
    private javax.swing.JMenuItem menuRelVenProdutos;
    private javax.swing.JMenuItem menuRelVenServicos;
    private javax.swing.JMenu menuRelVendas;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuResCadastrarReserva;
    private javax.swing.JMenuItem menuResConsultarReserva;
    private javax.swing.JMenuItem menuResFinalizarReserva;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSegFazBackup;
    private javax.swing.JMenuItem menuSegRestBackup;
    private javax.swing.JMenu menuSeguranca;
    private javax.swing.JMenuItem menuSerCadastrar;
    private javax.swing.JMenuItem menuSerConsultar;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenuItem menuVendasProdutos;
    private javax.swing.JMenuItem menuVendasServicos;
    // End of variables declaration//GEN-END:variables
}
